name: social_media_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.15.9
  firebase_auth: ^4.17.9
  firebase_core: ^2.27.1
  firebase_storage: ^11.6.10
  flutter:
    sdk: flutter
  flutter_holo_date_picker: ^1.1.3
  flutter_riverpod: ^2.5.1
  fluttertoast: ^8.2.4
  font_awesome_icon_class: ^0.0.6
  gap: ^3.0.1
  google_fonts: ^6.2.0
  image_picker: ^1.0.7
  jiffy: ^6.2.2
  uuid: ^4.3.3
  video_player: ^2.8.3
  file_picker: ^8.0.0+1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
