// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnzMafRy1fO3j6ycDLOFWjmodfEwQfVjI',
    appId: '1:1078996231205:android:26001f37c8dcf44cd08bcc',
    messagingSenderId: '1078996231205',
    projectId: 'social-media-app-25ec9',
    storageBucket: 'social-media-app-25ec9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB53cv9_lY74E2eEfKtZhyjPj8K3QnpesQ',
    appId: '1:1078996231205:ios:c4e99f6fb8b546c4d08bcc',
    messagingSenderId: '1078996231205',
    projectId: 'social-media-app-25ec9',
    storageBucket: 'social-media-app-25ec9.appspot.com',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB53cv9_lY74E2eEfKtZhyjPj8K3QnpesQ',
    appId: '1:1078996231205:ios:c4e99f6fb8b546c4d08bcc',
    messagingSenderId: '1078996231205',
    projectId: 'social-media-app-25ec9',
    storageBucket: 'social-media-app-25ec9.appspot.com',
    iosBundleId: 'com.example.socialMediaApp',
  );
}
